export const SET_LOGGED_USER = "SET_LOGGED_USER";
export const TOGGLE_CART_DROPDOWN = "TOGGLE_CART_DROPDOWN";
export const TOGGLE_USER_DROPDOWN = "TOGGLE_USER_DROPDOWN"
export const SHOP_ITEM_SELECTED = 'SHOP_ITEM_SELECTED';
export const TOTAL_CART_ITEMS = 'TOTAL_CART_ITEMS';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const INCREASE_ITEM_QUANTITY = 'INCREASE_ITEM_QUANTITY';
export const DECREASE_ITEM_QUANTITY = 'DECREASE_ITEM_QUANTITY';
export const CHOOSE_FILE = 'CHOOSE_FILE';

export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';
export const FETCH_COLLECTIONS_FAILURE = 'FETCH_COLLECTIONS_FAILURE';
